source 'https://rubygems.org'

platform :mri do
  gem 'byebug'
end

gem 'mongo', path: '../../ruby-driver'
#gem 'mongo', git: 'https://github.com/mongodb/mongo-ruby-driver'

gem 'faraday'
gem 'activesupport'
gem 'childprocess'
gem 'ffi'
gem 'puma'
gem 'sinatra'
gem 'mongoid'
gem 'typhoeus'
