#!/usr/bin/env ruby

#require 'active_support/core_ext/hash'
require 'fileutils'
#require 'yaml'

if ARGV.empty?
  raise "Usage: run-app-server config-file"
end

#config = YAML.load(File.read(ARGV.shift)).deep_symbolize_keys

#ENV['MONGODB_URI'] = config[:uri]

ENV['CONFIG_PATH'] = ARGV.shift

FileUtils.rm_f('server.log')

exec('puma config.puma.ru "$@" -w 3 -t 0:3 |tee server.log')
