#!/usr/bin/env ruby

type = ARGV.shift
unless %w(server test monitor).include?(type)
  raise "Bogus type #{type}"
end

case type
when 'server'

  require 'active_support/core_ext/hash'
  require 'fileutils'
  require 'yaml'

  if ARGV.empty?
    raise "Usage: run-app-server config-file"
  end

  config_path = ARGV.shift
  config = YAML.load(File.read(config_path)).deep_symbolize_keys

  ENV['CONFIG_PATH'] = config_path

  FileUtils.rm_f('server.log')

  exec("puma config.puma.ru \
  -w #{config[:puma_workers]} -t #{config[:puma_threads]} \
  -p #{config[:puma_port]} \
  -q \
  |tee server.log")

when 'test'

  require_relative './test_app'

  config_path = ARGV.shift or raise 'need config file'
  AppTester.new(config_path).run

when 'monitor'

  require_relative './deployment_monitor'

  DeploymentMonitor.new(ARGV.shift).run

else
  raise 'Should not get here'
end
