development:
  clients:
    default:
      database: mongoid
      hosts:
        - localhost:14400
      options:
        server_selection_timeout: 1
        #log_level: :warn
        
    fle:
      database: mongoid
      hosts:
        - localhost:14400
      options:
        server_selection_timeout: 1
        #log_level: :warn
  
        auto_encryption_options:
          key_vault_namespace: 'admin.datakeys'
          kms_providers:
            local:
              key: "z7iYiYKLuYymEWtk4kfny1ESBwwFdA58qMqff96A8ghiOcIK75lJGPUIocku8LOFjQuEgeIP4xlln3s7r93FV9J5sAE7zg8U"
          schema_map:
            blog_development.comments:
              properties:
                message:
                  encrypt:
                    keyId:
                      - !ruby/object:BSON::Binary
                        data: !binary |-
                          R/AgNcxASFiiJWKXqWGo5w==
                        type: :uuid
                    bsonType: "string"
                    algorithm: "AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic"
              bsonType: "object"  
  options:
    #log_level: :warn
    log_level: :debug
    #duplicate_fields_exception: true
    #raise_not_found_error: false
    #scope_overwrite_exception: true


xdevelopment:
  clients:
    default:
      database: mongoid
      hosts:
        - localhost:27741
      options:
        compressors: [zlib]
  options:
    log_level: :debug



xdevelopment:
  clients:
    default:
      database: databasename
      hosts:
        - localhost:27741
      options:
        user: 'admin'
        password: 'some-password'
        auth_mech: :scram
        auth_source: admin
        connect: :replica_set
        replica_set: replset
        ssl: true
        #ssl_ca_cert: ./some-certificate.pem
        ssl_verify: true
        server_selection_timeout: 1
  options:
    log_level: :debug
    
