# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 713defad3ead0db5e6906357ee7fb992a852ea229b1a40511cd16d16a089f3c0102f3852baf38bbd7ebac8b6c00205d718014be4fed1f33290d4d7368b605f3a

test:
  secret_key_base: 3daec1a6c07a4c0ea63f7c04d4fa08c4100f019cf580c2cc53f48ee35957ac19cfa3b838dbab18e9bd55fb3fd0c3c758ac37ef1e9e648ac68d2f2fe7e709e35b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
