# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks


task 'test-embedding' => :environment do
  Band.destroy_all

  Band.create!(name: 'SUN Project', cities: [City.new(name: 'London')])

  band = Band.where('cities.name' => 'London').only(:cities).first
  p band
  p band.cities

end
