#!/bin/sh

set -e

hosts="node1.1337.cx node2.1337.cx node3.1337.cx"

for host in $hosts; do
  ssh admin@$host '
    sudo apt update &&
    sudo apt install -y git &&
    rm -rf dev &&
    git clone https://github.com/p-mongo/dev &&
    cd dev &&
    ./script/install-mongodb
  '
done
