# frozen_string_literal: true

source "https://rubygems.org"
gem 'byebug'
gem 'mongo', '~> 2.11.0'
gem 'bson', '~> 4.6.0'
#gem 'bson', path: '../../apps/mongo/bson-ruby'
#gem 'mongoid'
gem 'mongoid' , path: '../../apps/mongo/mongoid'
